# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f23cd624443e6546ac057f4611f2e6f6f70119b490bcb30907231f39d5521e1e167885ca950449fc0e1699a5c1cfeea28e474047f48416bc81274cdb070adb52

test:
  secret_key_base: 17ba8f14ec71db9dfdb009ffea6773d67603f176dd5a19be734678c466cc3ffe5517464c05be9c5b613cf4eb5c68c188eaf4cab20348367cf5409bcb8018d16c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
